import '@pnp/sp/lists';
import '@pnp/sp/items';
import { IRenderListDataAsStreamResult } from '@pnp/sp/lists';
import { FieldTypes, IFieldInfo } from '@pnp/sp/fields';
import { IDropdownOption } from 'office-ui-fabric-react';
import { IViewInfo } from '@pnp/sp/views';
import { IItemUpdateResult } from '@pnp/sp/items';
import { ITypedHash } from '@pnp/common';
export declare const dateFormat: (value: number | Date | string, format: string, locale: string) => string | number | Date;
export declare const numberFormat: (value: number, format: string) => string;
export declare const validateSiteExists: (value: string) => Promise<string>;
export declare const getItemsUsingRenderListDataAsStream: (siteUrl: string, listId: string, viewXmlCode: string, nextHref?: string) => Promise<IRenderListDataAsStreamResult>;
export declare const useDebounce: (value: string, delay: number) => string;
export declare const createSearchQueryViewXml: (viewXmlCode: string, searchFields: IFieldInfo[], searchTerm: string) => string;
export declare const searchFieldTypes: FieldTypes[];
export declare const getSiteLocale: (siteUrl: string) => Promise<string>;
export declare const getListFields: (siteUrl: string, listId: string) => Promise<IFieldInfo[]>;
export declare const getListViewXml: (siteUrl: string, listId: string, viewId: string) => Promise<IViewInfo>;
export declare const getSearchFieldsFromOptions: (options: IDropdownOption[]) => IFieldInfo[];
export declare const updateListItem: (siteUrl: string, listId: string, itemId: number, properties: ITypedHash<unknown>) => Promise<IItemUpdateResult>;
export declare const addListItem: (siteUrl: string, listId: string, properties: ITypedHash<unknown>) => Promise<IItemUpdateResult>;
export declare const getNamedAttributeValue: (element: HTMLElement, attributeName: string) => string | null;
//# sourceMappingURL=Utilities.d.ts.map