declare const styles: {
    tableViewer: string;
    tableViewerHeader: string;
    searchBox: string;
    tabBar: string;
    barGrid: string;
    chartPrefix: string;
    chartBar: string;
    chartLabel: string;
    barCell: string;
    bar: string;
    barLabel: string;
    tableContainer: string;
    headerGrid: string;
    tableHeaderCell: string;
    sortIcon: string;
    footerGrid: string;
    tableFooterCell: string;
    tableGrid: string;
    tableCell: string;
    numberCell: string;
    editCell: string;
    iconCell: string;
    tableDataContent: string;
    highlight: string;
    personHolder: string;
    error: string;
    workbenchPageContent: string;
};
export default styles;
//# sourceMappingURL=TableViewer.module.scss.d.ts.map