declare const styles: {
    tableViewer: string;
    tableViewerHeader: string;
    searchBox: string;
    tabBar: string;
    tableContainer: string;
    tableGrid: string;
    tableHeaderCell: string;
    tableCell: string;
    tableDataContent: string;
    tableCellClamped: string;
    tableCellClamped1: string;
    tableCellClamped2: string;
    tableCellClamped3: string;
    tableCellClamped4: string;
    tableCellClamped5: string;
    ID: string;
    Title: string;
    BSADescription: string;
    singlechoice: string;
    multichoice: string;
    BSAColor: string;
    BSAStart: string;
    BSAEnd: string;
    PersonField: string;
    Stack: string;
    error: string;
};
export default styles;
//# sourceMappingURL=TableViewer.module.scss.d.ts.map